name1 = input("Enter Player Ones Name: ")
name2 = input("Enter Player Twos Name: ")
print("      |         |    ")
print("      |         |    ")
print("      |         |    ")
print("------------------------")
print("      |         |    ")
print("      |         |    ")
print("      |         |    ")
print("------------------------")
print("      |         |    ")
print("      |         |    ")
print("      |         |    ")
while True:
    print("Player Ones Turn")
    row = int(input("Row Number (0, 1, 2): "))
    colum = int(input("Colun Number (0, 1, 2): "))
    if row == 0 and colum == 0:
        print("      |         |    ")
        print("  0   |         |    ")
        print("      |         |    ")
        print("------------------------")
        print("      |         |    ")
        print("      |         |    ")
        print("      |         |    ")
        print("------------------------")
        print("      |         |    ")
        print("      |         |    ")
        print("      |         |    ")